-- =====================================================================
-- jetinno-qpay-bridge — migration 001_core.sql
-- Portable Postgres 15+. NO Supabase-only objects: runs on plain postgres
-- (Docker) so the e2e can apply it. RLS/auth lives in 002.
-- Verified: applies clean in one transaction on postgres:16-alpine.
-- =====================================================================

begin;

create extension if not exists pgcrypto;

create schema if not exists app;
comment on schema app is 'Server-side helpers. Not exposed through PostgREST.';

create or replace function app.touch_updated_at() returns trigger
language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;


-- =====================================================================
-- 1. TENANTS
-- =====================================================================
create table public.owners (
  id            uuid primary key default gen_random_uuid(),
  name          text not null,
  contact_phone text,
  contact_email text,
  status        text not null default 'active' check (status in ('active','suspended')),
  notes         text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
comment on table public.owners is 'A business that bought machines. Their machines'' money lands in their own QPay merchant account.';
create trigger owners_touch before update on public.owners
  for each row execute function app.touch_updated_at();


-- =====================================================================
-- 2. CREDENTIALS — ciphertext only; the key never enters Postgres
-- =====================================================================
create table public.qpay_credentials (
  id            uuid primary key,   -- app-generated: it is part of the AEAD AAD
  owner_id      uuid not null references public.owners(id) on delete restrict,
  label         text not null,

  sealed        text not null,      -- v1.<keyId>.<iv>.<tag>.<ct>, holds {username,password,invoiceCode}
  key_id        text not null,      -- denormalised copy of the id INSIDE `sealed`; rotation index only
  fingerprint   text not null,      -- keyed HMAC-SHA256 over lower(username)||':'||invoice_code
  invoice_code_hint text,           -- last 4 chars only, for support

  is_active     boolean not null default true,
  last_verified_at timestamptz,
  last_error    text,
  last_error_at timestamptz,
  auth_fail_count integer not null default 0,

  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),

  constraint qpay_credentials_owner_label_key unique (owner_id, label),
  constraint qpay_credentials_id_owner_key    unique (id, owner_id),
  constraint qpay_credentials_sealed_shape    check (sealed like 'v1.%'),
  constraint qpay_credentials_fp_shape        check (fingerprint ~ '^[0-9a-f]{64}$')
);
comment on column public.qpay_credentials.id is
  'Generated by the application BEFORE encrypting: the id is bound into the AEAD additional data together with owner_id. No DB default on purpose — a forgotten app-side id must fail loudly.';
comment on column public.qpay_credentials.sealed is
  'AES-256-GCM. AAD = ''v1|qpay_credentials:<id>|owner:<owner_id>''. Relocating this blob to another row, or re-parenting this row to another owner, fails authentication.';
comment on column public.qpay_credentials.fingerprint is
  'KEYED HMAC (CRED_FP_KEY), not a bare hash: a bare sha256 of a short structured username is brute-forceable from a dump.';

create unique index qpay_credentials_active_fingerprint_key
  on public.qpay_credentials (fingerprint) where is_active;
create index qpay_credentials_key_id_idx on public.qpay_credentials (key_id);
create trigger qpay_credentials_touch before update on public.qpay_credentials
  for each row execute function app.touch_updated_at();


-- =====================================================================
-- 3. MACHINES
-- =====================================================================
create table public.machines (
  id                 uuid primary key default gen_random_uuid(),
  owner_id           uuid not null,
  qpay_credential_id uuid not null,

  device_no          text not null,
  label              text,
  location           text,

  -- notifyUrl is NOT taken from the request body. Trust-on-first-use: the
  -- first signed getQrCode pins it here, every later request uses this value.
  notify_url         text,
  notify_url_pinned_at timestamptz,

  amount_divisor     integer not null default 100 check (amount_divisor in (1,100)),
  abandon_after_ms   integer not null default 600000 check (abandon_after_ms between 60000 and 3600000),

  status             text not null default 'active' check (status in ('active','disabled','retired')),
  installed_at       timestamptz,
  last_seen_at       timestamptz,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),

  constraint machines_device_no_key unique (device_no),
  constraint machines_id_owner_key  unique (id, owner_id),
  constraint machines_owner_fk foreign key (owner_id) references public.owners(id) on delete restrict,
  -- A machine can only be wired to a credential belonging to its OWN owner.
  -- Misrouted money becomes unrepresentable, not merely unlikely.
  constraint machines_credential_owner_fk
    foreign key (qpay_credential_id, owner_id)
    references public.qpay_credentials (id, owner_id) on delete restrict
);
comment on column public.machines.device_no is
  'Jetinno deviceNo. Globally unique: it is the only routing key the machine sends, so it must resolve to exactly one owner.';
comment on column public.machines.amount_divisor is
  '100 = machine sends cents (100000 -> 1000 MNT); 1 = machine sends tugrik. Confirm from the first live getQrCode log per model.';
create trigger machines_touch before update on public.machines
  for each row execute function app.touch_updated_at();


create table public.machine_assignments (
  id                 bigint generated always as identity primary key,
  machine_id         uuid not null references public.machines(id) on delete cascade,
  owner_id           uuid not null references public.owners(id) on delete restrict,
  qpay_credential_id uuid not null references public.qpay_credentials(id) on delete restrict,
  effective_from     timestamptz not null default now(),
  effective_to       timestamptz,
  reason             text,
  created_at         timestamptz not null default now(),
  constraint machine_assignments_range_chk check (effective_to is null or effective_to > effective_from)
);
create index machine_assignments_machine_idx on public.machine_assignments (machine_id, effective_from desc);
create unique index machine_assignments_one_open_key on public.machine_assignments (machine_id) where effective_to is null;


-- =====================================================================
-- 4. ORDERS — replaces the in-memory Map
-- =====================================================================
create table public.orders (
  id                     uuid primary key default gen_random_uuid(),

  machine_id             uuid not null,
  owner_id               uuid not null,   -- snapshot: immutable revenue attribution
  qpay_credential_id     uuid not null,   -- snapshot: settle must query the merchant that issued the invoice

  order_no               text not null,
  device_no              text not null,
  notify_url             text not null,   -- copied from machines, never from the request body
  product_id             text,
  product_name           text,
  raw_order_amount       text not null,   -- verbatim: it is a signed field
  amount_divisor         integer not null,
  amount_mnt             integer not null check (amount_mnt > 0),
  paid_amount_mnt        integer,

  qpay_sender_invoice_no text not null check (char_length(qpay_sender_invoice_no) between 1 and 45),
  invoice_attempt        integer not null default 1 check (invoice_attempt between 1 and 9),
  qpay_invoice_id        text,
  qpay_payment_id        text,
  callback_url           text not null,
  qr_code                text check (qr_code is null or char_length(qr_code) <= 128),
  qr_text_len            integer,

  status                 text not null default 'creating'
    check (status in ('creating','awaiting_payment','settling','payment_confirmed',
                      'paid','cancelled','failed','orphaned','needs_human')),
  settle_lease_until     timestamptz,
  settle_lease_owner     text,
  settle_attempts        integer not null default 0,
  notify_attempts        integer not null default 0,
  notify_sent_at         timestamptz,     -- set BEFORE the fetch: "assume delivered"
  last_error             text,
  last_error_at          timestamptz,

  payment_confirmed_at   timestamptz,
  notified_at            timestamptz,
  product_done_at        timestamptz,
  product_done_ok        boolean,
  cancelled_at           timestamptz,

  expires_at             timestamptz not null default now() + interval '10 minutes',
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),

  constraint orders_machine_owner_fk foreign key (machine_id, owner_id)
    references public.machines (id, owner_id) on delete restrict,
  constraint orders_credential_owner_fk foreign key (qpay_credential_id, owner_id)
    references public.qpay_credentials (id, owner_id) on delete restrict,

  constraint orders_machine_order_no_key unique (machine_id, order_no),
  constraint orders_sender_invoice_key unique (qpay_credential_id, qpay_sender_invoice_no),

  constraint orders_lease_shape check (status <> 'settling' or settle_lease_until is not null),
  constraint orders_confirmed_shape check (status not in ('payment_confirmed','paid') or payment_confirmed_at is not null),
  constraint orders_paid_shape check (status <> 'paid' or (payment_confirmed_at is not null and notified_at is not null)),
  constraint orders_paid_amount_shape check (status <> 'paid' or paid_amount_mnt = amount_mnt),
  constraint orders_live_needs_invoice
    check (status not in ('awaiting_payment','settling','payment_confirmed','paid') or qpay_invoice_id is not null)
);
comment on column public.orders.owner_id is
  'Denormalised from machines on purpose. Reselling a machine must not retroactively move last month''s revenue to the new owner. The composite FK stops it drifting at write time.';
comment on column public.orders.notify_sent_at is
  'Stamped immediately BEFORE the notify fetch, not after. A brew takes 30-60s, so a lost ACK must be treated as delivered until the grace window passes — otherwise the retry brews a second cup.';
comment on column public.orders.raw_order_amount is
  'Verbatim, because reproducing the Jetinno MD5 needs the exact string the machine sent, leading zeros included.';

create index orders_order_no_idx on public.orders (order_no);
create unique index orders_qpay_invoice_id_key on public.orders (qpay_invoice_id) where qpay_invoice_id is not null;
create unique index orders_qpay_payment_id_key on public.orders (qpay_payment_id) where qpay_payment_id is not null;
create index orders_sweep_idx on public.orders (expires_at)
  where status in ('creating','awaiting_payment','settling');
create index orders_owed_idx on public.orders (payment_confirmed_at)
  where status in ('payment_confirmed','settling');
create index orders_owner_created_idx on public.orders (owner_id, created_at desc);
create trigger orders_touch before update on public.orders
  for each row execute function app.touch_updated_at();


-- =====================================================================
-- 5. AUDIT / ERROR SURFACE
-- =====================================================================
create table public.order_events (
  id         bigint generated always as identity primary key,
  order_id   uuid references public.orders(id) on delete cascade,
  owner_id   uuid references public.owners(id) on delete cascade,
  machine_id uuid references public.machines(id) on delete set null,
  kind       text not null,
  detail     jsonb not null default '{}'::jsonb,
  at         timestamptz not null default now()
);
comment on table public.order_events is
  'Append-only. NEVER store the expected MD5 signature here — that hands out a forgeable value.';
create index order_events_order_idx on public.order_events (order_id, at desc);
create index order_events_owner_idx on public.order_events (owner_id, at desc);
create index order_events_kind_idx  on public.order_events (kind, at desc);

create table public.ingest_errors (
  id        bigint generated always as identity primary key,
  at        timestamptz not null default now(),
  path      text not null,
  device_no text,
  order_no  text,
  reason    text not null,
  payload   jsonb,
  remote_ip inet
);
create index ingest_errors_at_idx on public.ingest_errors (at desc);
create index ingest_errors_device_idx on public.ingest_errors (device_no, at desc);

-- The rows an attacker actually edits to redirect money. Trigger-written; the
-- application never writes this table directly.
create table public.admin_audit (
  id         bigint generated always as identity primary key,
  at         timestamptz not null default now(),
  table_name text not null,
  op         text not null,
  row_id     text,
  db_user    text not null default current_user,
  before     jsonb,
  after      jsonb,
  sealed_changed boolean not null default false
);
create index admin_audit_at_idx on public.admin_audit (at desc);
create index admin_audit_row_idx on public.admin_audit (table_name, row_id, at desc);

create or replace function app.audit_row() returns trigger
language plpgsql security definer set search_path = '' as $$
declare
  b jsonb := case when tg_op = 'INSERT' then null else to_jsonb(old) end;
  a jsonb := case when tg_op = 'DELETE' then null else to_jsonb(new) end;
begin
  insert into public.admin_audit (table_name, op, row_id, before, after, sealed_changed)
  values (
    tg_table_name, tg_op,
    coalesce(a ->> 'id', b ->> 'id'),
    b - 'sealed', a - 'sealed',
    coalesce(b ->> 'sealed', '') is distinct from coalesce(a ->> 'sealed', '')
  );
  return null;
end $$;

create trigger machines_audit after insert or update or delete on public.machines
  for each row execute function app.audit_row();
create trigger qpay_credentials_audit after insert or update or delete on public.qpay_credentials
  for each row execute function app.audit_row();
create trigger owners_audit after insert or update or delete on public.owners
  for each row execute function app.audit_row();


-- =====================================================================
-- 6. CONCURRENCY — the lease that replaces the in-process `settling` flag
-- =====================================================================
/*
 * Atomic claim. Exactly one caller, across every instance, gets a row back.
 *
 * RETURNS SETOF, never a bare composite: a function returning a composite type
 * yields one all-NULL row when the UPDATE matches nothing, which every driver
 * reports as "1 row" — inverting the guard into a guaranteed double-dispense.
 *
 * Refusals, in order of importance:
 *   product_done_at set          -> the cup already came out; never again.
 *   notify_sent_at within grace  -> we told the machine and are still inside its
 *                                   brew time. A lost ACK must not brew twice.
 *   settle_attempts >= cap       -> stop hammering QPay; a human takes over.
 *   status settling + live lease -> another instance holds it.
 */
create or replace function app.claim_order_for_settle(
  p_order_id             uuid,
  p_lease_seconds        integer default 60,
  p_instance             text    default null,
  p_notify_grace_seconds integer default 120,
  p_max_attempts         integer default 10
) returns setof public.orders
language sql volatile as $$
  update public.orders o
     set status             = 'settling',
         settle_lease_until = now() + make_interval(secs => p_lease_seconds),
         settle_lease_owner = p_instance,
         settle_attempts    = o.settle_attempts + 1,
         updated_at         = now()
   where o.id = p_order_id
     and o.product_done_at is null
     and o.settle_attempts < p_max_attempts
     and (o.notify_sent_at is null
          or o.notify_sent_at < now() - make_interval(secs => p_notify_grace_seconds))
     and (o.status in ('awaiting_payment','payment_confirmed')
          or (o.status = 'settling' and o.settle_lease_until < now()))
  returning o.*;
$$;

/* Money confirmed, machine not told yet. Refuses to record a mismatched amount. */
create or replace function app.mark_payment_confirmed(
  p_order_id      uuid,
  p_payment_id    text,
  p_paid_amount   integer,
  p_lease_seconds integer default 60
) returns setof public.orders
language sql volatile as $$
  update public.orders o
     set qpay_payment_id      = coalesce(o.qpay_payment_id, p_payment_id),
         paid_amount_mnt      = p_paid_amount,
         payment_confirmed_at = coalesce(o.payment_confirmed_at, now()),
         settle_lease_until   = now() + make_interval(secs => p_lease_seconds),
         updated_at           = now()
   where o.id = p_order_id
     and o.status = 'settling'
     and p_paid_amount = o.amount_mnt
  returning o.*;
$$;

/* Stamped immediately BEFORE the notify fetch. */
create or replace function app.mark_notify_sent(p_order_id uuid)
returns setof public.orders
language sql volatile as $$
  update public.orders o
     set notify_sent_at  = now(),
         notify_attempts = o.notify_attempts + 1,
         updated_at      = now()
   where o.id = p_order_id and o.status = 'settling'
  returning o.*;
$$;

/* The machine ACKed. Terminal success. */
create or replace function app.finish_settle(p_order_id uuid)
returns setof public.orders
language sql volatile as $$
  update public.orders o
     set status             = 'paid',
         notified_at        = coalesce(o.notified_at, now()),
         settle_lease_until = null,
         settle_lease_owner = null,
         last_error         = null,
         updated_at         = now()
   where o.id = p_order_id and o.status = 'settling'
  returning o.*;
$$;

/*
 * Release without success: back to a retryable state the drain worker owns.
 * p_count_attempt=false undoes the claim's increment, for benign outcomes such
 * as "not paid yet". Without it, anyone hitting the public callback route
 * could burn a legitimate order's ten attempts and force it to needs_human.
 */
create or replace function app.release_settle(
  p_order_id uuid,
  p_error text default null,
  p_count_attempt boolean default true
) returns setof public.orders
language sql volatile as $$
  update public.orders o
     set status = case when o.payment_confirmed_at is not null
                       then 'payment_confirmed' else 'awaiting_payment' end,
         settle_attempts = case when p_count_attempt then o.settle_attempts
                                else greatest(o.settle_attempts - 1, 0) end,
         settle_lease_until = null,
         settle_lease_owner = null,
         last_error    = coalesce(p_error, o.last_error),
         last_error_at = case when p_error is null then o.last_error_at else now() end,
         updated_at    = now()
   where o.id = p_order_id and o.status = 'settling'
  returning o.*;
$$;

/* Terminal give-up. Nothing retries a needs_human row; a person does. */
create or replace function app.give_up(p_order_id uuid, p_error text)
returns setof public.orders
language sql volatile as $$
  update public.orders o
     set status = 'needs_human',
         settle_lease_until = null,
         settle_lease_owner = null,
         last_error = p_error,
         last_error_at = now(),
         updated_at = now()
   where o.id = p_order_id
     and o.status in ('creating','awaiting_payment','settling','payment_confirmed')
  returning o.*;
$$;

/* Sweeper claim: expired unpaid QRs. Never touches payment_confirmed. */
create or replace function app.claim_abandoned_orders(
  p_limit integer default 50,
  p_lease_seconds integer default 60,
  p_instance text default null,
  p_max_attempts integer default 10
) returns setof public.orders
language sql volatile as $$
  with candidate as (
    select o.id from public.orders o
     where o.expires_at < now()
       and o.status in ('creating','awaiting_payment','settling')
       and o.settle_attempts < p_max_attempts
       and (o.status <> 'settling' or o.settle_lease_until < now())
     order by o.expires_at
     limit p_limit
     for update skip locked
  )
  update public.orders o
     set status = 'settling',
         settle_lease_until = now() + make_interval(secs => p_lease_seconds),
         settle_lease_owner = p_instance,
         settle_attempts = o.settle_attempts + 1,
         updated_at = now()
    from candidate c
   where o.id = c.id
  returning o.*;
$$;

/* Drain worker: money in, machine not told (or told and never ACKed). */
create or replace function app.claim_unnotified_orders(
  p_limit integer default 20,
  p_lease_seconds integer default 60,
  p_instance text default null,
  p_notify_grace_seconds integer default 120,
  p_max_attempts integer default 10
) returns setof public.orders
language sql volatile as $$
  with candidate as (
    select o.id from public.orders o
     where o.status in ('payment_confirmed','settling')
       and o.product_done_at is null
       and o.settle_attempts < p_max_attempts
       and o.payment_confirmed_at < now() - interval '30 seconds'
       and (o.notify_sent_at is null
            or o.notify_sent_at < now() - make_interval(secs => p_notify_grace_seconds))
       and (o.status <> 'settling' or o.settle_lease_until < now())
     order by o.payment_confirmed_at
     limit p_limit
     for update skip locked
  )
  update public.orders o
     set status = 'settling',
         settle_lease_until = now() + make_interval(secs => p_lease_seconds),
         settle_lease_owner = p_instance,
         settle_attempts = o.settle_attempts + 1,
         updated_at = now()
    from candidate c
   where o.id = c.id
  returning o.*;
$$;

/*
 * The machine says the cup came out. Load-bearing, not bookkeeping: this
 * permanently blocks every future settle claim.
 *
 * Only accepted for an order we actually told to brew. A forged productdone
 * for an awaiting_payment order would otherwise poison it forever and stop
 * that machine selling.
 */
create or replace function app.record_product_done(p_order_id uuid, p_ok boolean)
returns setof public.orders
language sql volatile as $$
  update public.orders o
     set product_done_at = coalesce(o.product_done_at, now()),
         product_done_ok = coalesce(o.product_done_ok, p_ok),
         updated_at = now()
   where o.id = p_order_id
     and o.status in ('settling','payment_confirmed','paid')
  returning o.*;
$$;

create or replace function app.mark_cancelled(p_order_id uuid)
returns setof public.orders
language sql volatile as $$
  update public.orders o
     set status = 'cancelled', cancelled_at = now(),
         settle_lease_until = null, settle_lease_owner = null, updated_at = now()
   where o.id = p_order_id and o.status = 'settling' and o.payment_confirmed_at is null
  returning o.*;
$$;

commit;
